steps:
  - label: "Install Node.js and AWS CDK"
    commands:
      - which node || curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && apt-get install -y nodejs
      - npm install -g aws-cdk
      - echo "Node version:" && node --version
      - echo "NPM version:" && npm --version
      - echo "NPM global prefix:" && npm prefix -g
      - echo "CDK location:" && which cdk || echo "CDK not found in PATH"
      - ls -la "$(npm prefix -g)/bin/" | grep cdk || echo "CDK not in npm bin"

  - label: "Show CDK Diff"
    commands:
      - pip install -r requirements.txt
      - "$(npm prefix -g)/bin/cdk diff"

  - block: "Approve CDK Deploy?"

  - label: "Deploy CDK Stack"
    commands:
      - "$(npm prefix -g)/bin/cdk deploy --require-approval never"

  - label: "Sync Static Files to S3"
    commands:
      - aws s3 cp blog/site s3://www.shrirajchohan.com --recursive